export enum EPermissionName {
    DASHBOARD_ACCESS = 'DASHBOARD_ACCESS',
    MEMBER_MANAGEMENT = 'MEMBER_MANAGEMENT',
    PRODUCT_MANAGEMENT = 'PRODUCT_MANAGEMENT',
    ORDER_MANAGEMENT = 'ORDER_MANAGEMENT',
    RECIPE_MANAGEMENT = 'RECIPE_MANAGEMENT',
    BANNER_MANAGEMENT = 'BANNER_MANAGEMENT',
}